spotify_lookup.settings:
  type: config_object
  label: 'Spotify Lookup settings'
  mapping:
    client_id:
      type: string
      label: 'Spotify Client ID'
    client_secret:
      type: string
      label: 'Spotify Client Secret'
