discogs_lookup.settings:
  type: config_object
  label: "Discogs lookup settings"
  mapping:
    token:
      type: string
      label: "Discogs API token"
    api_uri:
      type: string
      label: "Discogs API URI"
      nullable: true
    max_hits:
      type: integer
      label: "Maximum number of results per search"
      nullable: true
